Make Transfer\Config customizable
SOF3/Capital pull request #13
Opened 2022-01-30 18:59 UTC by Swift-Strider

Allow `Transfer\Config` to be customized in `config.yml` under the key "transfer". I propose using MethodFactory to build classes implementing Method (right now, only CommandMethod), from a subkey of "transfer" (ex. transfer.pay). MethodFactory also has a static method `MethodFactory::writeDefaults()` that takes a parser and adds the default CommandMethods ( /pay, /takemoney, /addmoney ) to it.

### MethodFactory's Methods
```php
public static function build(Parser $parser, string $methodName): Method
public static function writeDefaults(Parser $parser): void
```

2022-01-31 01:47 UTC, SOF3 requested changes

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +    public static function build(Parser $parser, string $methodName) : Method
Please use code style consistent with the rest of the project.

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        The type of the method. Must be "command"
The concept of "method" is too abstract for users. Maybe just make a list called `commands` and all entries in the list are commands?

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        $src = self::parseLabelSelector($parser->enter("src", <<<'EOT'
Do not expose account labels to users directly. Transaction labels are fine, but for account labels, please use the Schema API.

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            The largest amount of currency that can be transferred.
```suggestion
            The maximum amount of money that can be transferred each time.
```

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            The smallest amount of currency that can be transferred.
```suggestion
            The minimum amount of money that can be transferred each time.
```

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            methods players use to move capital.
```suggestion
            how players earn and lose money.
```

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            EOT));
Just translations, no need to document too much, should be self explanatory anyway.

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +    public static function writeDefaults(Parser $parser) : void
Why does this function duplicate the above? What's the difference between the two functions?

2022-01-31 01:47 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            AccountLabels::ORACLE => OracleNames::TRANSFER,
With the new Schema API, payment commands can no longer be generalized in the config like this.

2022-01-31 04:23 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +    public static function writeDefaults(Parser $parser) : void
Did away with separating `MethodFactory::build()` and `MethodFactory::writeDefaults`.
Every class implementing Method should have a corresponding `MethodFactory::buildMethod()` function.

2022-02-01 04:34 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            AccountLabels::ORACLE => OracleNames::TRANSFER,
We're now using `parseTarget()`.

2022-02-05 08:04 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +        $schema = $schema->cloneWithConfig($parser, true);
If I use `$shema->cloneWithConfig($parser, false)` instead, it seems that the command would be able to take on many currencies (see `Currency::cloneWithConfig()`).
Should I change `true` to `false`? If I do, is my best option checking if the instanceof $schema is Currency and requiring currency as an argument when `$schema->defaultCurrency` is null or "~"?

2022-02-05 08:29 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +    private static function parseLabelSet(Parser $parser, $defaultEntries = []) : ParameterizedLabelSet
Should I move `MethodFactory::parseLabelSet()` to `ParameterizedLabelSet::parse()`? This would bring consistency with `AccountTarget::parse()` and `Messages::parse()`. Also if this function is moved, `MethodFactory::buildCommand()` could be moved to `CommandMethod::parse()` leaving `MethodFactory` to be safely deleted.

2022-02-05 15:55 UTC, SOF3 requested changes
Note to self: change merge base to `master` when merging.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +    public static function parse(Parser $parser, Schema $schema, string $defaultTarget = self::TARGET_SYSTEM) : self
Why does `$defaultTarget` need to be parameterized here?

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +     * @var $target self::TARGET_*
The convention in Capital uses `@var` instead of `@param` for constructor fields.

I'm not sure which one is better though. Better stay consistent before we change them all.

Also it should be `@param Type $name` not `@param $name Type`

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +     * @var $target self::TARGET_*
```suggestion
     * @param self::TARGET_* target
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +        $schema = $schema->cloneWithConfig($parser, true);
It should be `false`. If the user wants to limit to a single option, they can choose to specify only one currency in `allowed-currencies`.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +        $schema = $schema->cloneWithConfig($parser, true);
`expectComplete` means "I expect that this schema must be complete (`isComplete` returns true) after I parse this config". I should probably split them to two different methods for clarity though.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +            If "sender" is used, this command will only be usable by
Can compress to the same line. The convention is to split only when the line is really long, and split somewhere near the middle where the sentence is logically split (e.g. starts a new clause).

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +            players. (ex. not the console)
```suggestion
            players (i.e. cannot be used from console).
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Command.php
> +                    $sender->sendMessage(InfoAPI::resolve($this->method->messages->internalError, $info));
Can simply throw exception in this case. We do not need to self-heal if there is a bug in the plugin. The design goal is to be tolerant of user input, but be strict about developer (i.e. ourselves) input.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Command.php
> +            $srcLabels = $this->method->src->getSelector($sender, $recipient);
Accounts are created lazily. We need to migrate/create the account if the account does not exist.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Config.php
> +        $commandNames = array_filter($commandsParser->getKeys(), fn($command) => $command[0] !== "#");
I think `getKeys()` no longer returns `#` keys anymore.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +     * @phpstan-param self::TARGET_* $defaultTarget
No need to `phpstan-`, just `@param` directly.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Config.php
> +            If "default-op" is set to true, users must be OP'ed.
```suggestion
            Why document `default-op` here instead of near the `default-op` attribute?
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Config.php
> +            $commandsParser->failSafe(null, "There must be at least one method");
I don't think this is a good idea. There are legitimate cases where no commands are intended. Perhaps we need to tweak the `enter` logic a bit to allow specifying default content so that we can distinguish intentional empty arrays and auto-generated empty arrays.

Also, "method" is an internal term. Please use "command" in user-facing messages.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/DefaultCommand.php
> +
```suggestion

/**
 * Template for generated command entries in failsafe mode.
 * Only used as a parameter to `MethodBuilder::buildCommand`.
 */
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Config.php
> +                    internalError: '{red}An internal error occurred. Please try again.',
I wonder if we should extract this to somewhere common.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Config.php
> +                    Constants::LABEL_OPERATOR => "",
`Constants` was a hack when I hardcoded config. Should be fine to move `LABEL_OPERATOR` into a class constant in this class only, if it is not to be used elsewhere.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Config.php
> +                maximumAmount: 1000000,
Can we make this nullable?

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Messages.php
> +            $parser->expectString("notify-sender-success", $default?->notifySenderSuccess ?? "{green}notify-sender-success (override me!)", "Sent to command sender on success."),
What if we make this message more useful and include basic information like amount sent?

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Messages.php
> +            $parser->expectString("notify-sender-success", $default?->notifySenderSuccess ?? "{green}notify-sender-success (override me!)", "Sent to command sender on success."),
```suggestion
            $parser->expectString("notify-sender-success", $default?->notifySenderSuccess ?? "{green}notify-sender-success (change this!)", "Sent to command sender on success."),
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            This is the permission players must have.
```suggestion
            Users must have this permission to run this command.
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Config.php
> +            These slash commands initiate transfers.
There are no non-slash commands in PocketMine; users won't confuse this with Discord commands after all.

```suggestion
            These commands initiate transfers.
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            This is the name of the command that will be run.
But isn't the name already defined in the mapping key under `commands`?

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            It will be created for you.
I am not sure if this needs to be explained. Users probably won't care about this anyway.

Actually I wonder if we should even make this configurable. Why not just autogenerate it as `"capital.transfer.$commandName"`?

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        } elseif (($i = strpos($permission, " ")) !== false) {
is there a reason why this check is needed?

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            This requires the user of the command to have op permissions.
```suggestion
            If set to true, only ops can use this command
            (you can further configure this with permission plugins).
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            The "source" to take money from.
```suggestion
            The source account to deduct money from.
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            The "destination" to give money to.
```suggestion
            The destination account to add money to.
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            EOT);
Not necessary in this pull request, but I was thinking maybe we can add another `fee` parameter which is a service fee every time a payment occurs. This would make `minimum-amount` and `maximum-amount` more meaningful.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            how players earn and lose money.
```suggestion
            how players earn and lose money.
            Labels are formatted using InfoAPI syntax.
```

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        $messages = Messages::parse($parser->enter("messages", ""), $default?->messages);
Missing description?

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +    private static function parseLabelSet(Parser $parser, $defaultEntries = []) : ParameterizedLabelSet
:+1:

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        $names = array_filter($parser->getKeys(), fn($currency) => $currency[0] !== "#");
Unnecessary filter, again.

2022-02-05 15:55 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +                $parser->expectString($name, $value, "");
Might need changes in `Config\Parser` so that it does not generate `#` if description is empty.

2022-02-05 21:13 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +    public static function parse(Parser $parser, Schema $schema, string $defaultTarget = self::TARGET_SYSTEM) : self
`DefaultCommand::src` and `::dest` store the target as a string ('system'|'sender'|'recipient'), and it needs to be sent to `AccountTarget::parse()` for it to set the "of" key correspondingly.

2022-02-05 21:39 UTC, Swift-Strider commented on src/SOFe/Capital/ParameterizedLabelSet.php
> +    public static function parse(Parser $parser, $defaultEntries = []) : self
How should I deal with the following phpstan errors?
>  Method SOFe\Capital\ParameterizedLabelSet::parse() return type with generic class SOFe\Capital\ParameterizedLabelSet does not specify its types: I

> PHPDoc tag @var for variable $labelSet contains generic class SOFe\Capital\ParameterizedLabelSet but does not specify its types: I

For now, I have added them to the baseline.
# Now, back to the question!
I've considered using @template, but that requires that the function takes a parameter that references the `@template T of Info` type. I think this should be left at is, and the callers should just cast the returned value to be `@var ParameterizedLabelSet<WhatEverInfoYouWant> $returnedValue`.

2022-02-05 21:40 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        $messages = Messages::parse($parser->enter("messages", ""), $default?->messages);
I removed the description in fear of being too verbose; I can always add them back if you want.

2022-02-05 21:55 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        $names = array_filter($parser->getKeys(), fn($currency) => $currency[0] !== "#");
$labelNames wasn't being iterated through which I patched now.
```diff
-  foreach ($parser->getKeys() as $name) {
+  foreach ($labelNames as $name) {
|      $entries[$name] = $parser->expectString($name, "", "");
|  }
```
I think the filter is necessary as the call to `$parser->expectString()` may add an empty doc comment, the empty string passed as its third parameter.

2022-02-05 21:59 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        $names = array_filter($parser->getKeys(), fn($currency) => $currency[0] !== "#");
Ex. if the user puts a number on accident for a label value; `expectString()` will fail and reset that label's value to an empty string, and a comment will be added hence why I think the filter is needed.

2022-02-05 22:00 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +                $parser->expectString($name, $value, "");
Yes, I may as well do that in this PR if you don't mind.

2022-02-05 22:25 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +        $names = array_filter($parser->getKeys(), fn($currency) => $currency[0] !== "#");
This is now fixed. 7187abbf421c318112d3d6d907781ca1293dadf4

2022-02-05 22:49 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/Command.php
> +                    $sender->sendMessage(InfoAPI::resolve($this->method->messages->internalError, $info));
Fixed in fc62ad9f9e24f4e7073dca4a548a72bbf0050d1f

2022-02-05 22:53 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/Config.php
> +        $commandNames = array_filter($commandsParser->getKeys(), fn($command) => $command[0] !== "#");
Oh, it's now fixed in 630832fe39eab2f531872e0c96150f89964396cd.

2022-02-05 22:54 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/Config.php
> +            If "default-op" is set to true, users must be OP'ed.
Fixed in 9a8cc60d390b0cb0d28fa3a34aa380db7a066f63.

2022-02-05 23:38 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/Config.php
> +            $commandsParser->failSafe(null, "There must be at least one method");
Fixed in 52b4f5c3876aaf8d53ff6d495be8fe87721c9442.

I added `$parser->enterWithCreated()`. The method returns an array `[$parser, $wasCreated]`. I then use it to choose whether to leave "commands" empty or to auto-fill commands.

2022-02-05 23:46 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/DefaultCommand.php
> +
Fixed in 056805c31f2d65083d8d04d7a79b0780af76be19.

2022-02-05 23:52 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/Config.php
> +                    Constants::LABEL_OPERATOR => "",
I removed Constants all together ac193bacf8a9abbcd1b8ca5e45f8e4328a740706.

2022-02-05 23:56 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            This is the permission players must have.
Fixed in 42a009fc50fb334aff5fd5b96e32afb585eddafe.

2022-02-05 23:58 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/Config.php
> +            These slash commands initiate transfers.
Fixed in ce88f7e78023ffe09939780d008bc6aa2d9f38f1.

2022-02-06 02:59 UTC, SOF3 commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +                $parser->expectString($name, $value, "");
Yeah, just do  it in the same PR, don't waste time branching.

2022-02-06 02:59 UTC, SOF3 commented on src/SOFe/Capital/Transfer/Command.php
> +            $srcLabels = $this->method->src->getSelector($sender, $recipient);
I will deal with it later.

2022-02-06 03:03 UTC, SOF3 commented on src/SOFe/Capital/ParameterizedLabelSet.php
> +    public static function parse(Parser $parser, $defaultEntries = []) : self
If you use `@template`, it should auto infer anyway. The use of templates here is more as a way of documenting things than actually making phpstan detect something.

2022-02-06 08:49 UTC, Swift-Strider commented on src/SOFe/Capital/ParameterizedLabelSet.php
> +    public static function parse(Parser $parser, $defaultEntries = []) : self
Ok. I added extra entries to `phpstan-baseline.neon`, to suppress the following errors.
![image](https://user-images.githubusercontent.com/62265561/152673747-1d1250e5-513e-460c-a9a0-08f59e528737.png)

2022-02-06 09:01 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +                $parser->expectString($name, $value, "");
Done in b39c70be0ee1c0b30a5e2220284fe5d5faf2c0e5.

2022-02-06 09:06 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            how players earn and lose money.
Fixed. 3fedd9a0132896ce32c8b96688df0981bd3f630b

2022-02-06 09:08 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/AccountTarget.php
> +     * @var $target self::TARGET_*
Fixed 6adfe45ba088cfec7aec2a04a7ae009d22fc85f0.

2022-02-06 09:14 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            It will be created for you.
I don't see why not. I'll make this change soon.

2022-02-06 09:20 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            It will be created for you.
Done in 4a557bb14c3522cd1cedc1ac53a7f523c5dc63e7.

2022-02-06 09:25 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            This requires the user of the command to have op permissions.
Done. 6a3b5169bfe3c28bb61d2fb5b10159dca7983467

2022-02-06 10:22 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            This is the name of the command that will be run.
Yes, now fixed. 32e55322efdb653458efbb00afd34a926e3246a3

2022-02-06 10:24 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            The "destination" to give money to.
Fixed. 3784bfbf335052e4a61b2b0da53296e50aa5bec9

2022-02-06 10:25 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            The "source" to take money from.
Fixed. 3784bfbf335052e4a61b2b0da53296e50aa5bec9

2022-02-06 11:46 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            EOT);
In 41f6daaa26de06ad99dc5ec7cf2670c915fab0bc I found an issue with $fee.
Imagine this scenario, a command is made with a `$rate > 1` and a `$fee > 0`. Quoted from Command.php:
>TODO: Possibly add a `$api->transact3()`?
>
>To satisfy this transaction we need to:
> 1. send $sinkAmount (`==` to $fee) from src to oracle,
> 2. send $transferAmount from src to dest, and
> 3. send $sourceAmount from oracle to dest.

2022-02-06 14:55 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/MethodFactory.php
> +            EOT);
Done 6d593e94ef8a07767aedaf7bd2abe41f3aee5753. The fee is now either sent directly to the oracle from the source or accounted for by deducting the fee from the amount of money the destination would have gotten from the oracle.

2022-02-06 14:57 UTC, Swift-Strider commented on src/SOFe/Capital/Transfer/Config.php
> +                maximumAmount: 1000000,
So, when `$maximumAmount === 0` there will be no cap on the amount of money that can be transferred? I will work on this now.

2022-02-12 07:20 UTC, merged