Added payWithBalance()
SOF3/Capital pull request #42
Opened 2022-04-30 18:04 UTC by JavierLeon9966

2022-05-01 01:06 UTC, SOF3 requested changes

2022-05-01 01:06 UTC, SOF3 commented on src/SOFe/Capital/Capital.php
> +        Closure $promise,
This closure is not a promise at all. It's just a balance transformer.

2022-05-01 01:06 UTC, SOF3 commented on src/SOFe/Capital/Capital.php
> +        $srcAccount = $srcAccounts[0]; // must have at least one because it was lazily created
to-do: it's supposed to include all accounts, not just the first one

2022-05-04 03:30 UTC, JavierLeon9966 commented on src/SOFe/Capital/Capital.php
> +        Closure $promise,
Maybe it should be appropriate to rename it to `$convert`. I’ll change it to that for now

2022-05-04 03:30 UTC, JavierLeon9966 commented on src/SOFe/Capital/Capital.php
> +        $srcAccount = $srcAccounts[0]; // must have at least one because it was lazily created
Should this problem wait until other methods like `pay()` and `payUnequal()` finally include all accounts?

2022-05-04 05:45 UTC, SOF3 commented on src/SOFe/Capital/Capital.php
> +        $srcAccount = $srcAccounts[0]; // must have at least one because it was lazily created
Yes, this is an issue for #2 , which I am not sure how to fix yet.

2022-05-04 05:46 UTC, SOF3 approved these changes
Consider adding a test case of convenient.

2022-05-04 11:46 UTC, SOF3 commented
CI is failing because of known issues; I will fix it tonight.

2022-05-23 02:02 UTC, SOF3 commented
@JavierLeon9966 code style error. Please `make fmt`.

2022-05-23 02:04 UTC, SOF3 requested changes

2022-05-23 02:04 UTC, SOF3 commented on src/SOFe/Capital/Capital.php
> +    public function payWithBalance(
Rename this to `payAdaptive`?

2022-05-23 02:04 UTC, SOF3 commented on src/SOFe/Capital/Capital.php
> +        do{
Code style issue, please `make fmt`.

2022-05-26 06:34 UTC, JavierLeon9966 commented on src/SOFe/Capital/Capital.php
> +    public function payWithBalance(
That actually sounds good

2022-05-27 05:14 UTC, SOF3 commented on src/SOFe/Capital/Capital.php
> +                $retry = false;
Why do we need a separate retry variable instead of simply `break;`? Personally I'm not a fan of do-while loops. Maybe just do `while(true)` and `break`?

2022-05-27 05:14 UTC, SOF3 commented on src/SOFe/Capital/Capital.php
> +
```suggestion
```

2022-05-28 15:32 UTC, JavierLeon9966 commented on src/SOFe/Capital/Capital.php
> +                $retry = false;
Yeah, I guess that should be fine

2022-05-29 04:03 UTC, SOF3 approved these changes

2022-05-29 04:03 UTC, merged

2022-05-29 04:04 UTC, SOF3 commented
@JavierLeon9966 would you also like to contribute a set-balance command based on payWithBalance?

2022-05-29 06:23 UTC, JavierLeon9966 commented
> @JavierLeon9966 would you also like to contribute a set-balance command based on payWithBalance?

Sure, but how would `payAdaptive()` fit into this?

2022-05-29 12:43 UTC, SOF3 commented
maybe
```php
function setBalance($otherArgs, int $target) {
    yield from payWithBalance($otherArgs, fn($current) => $target - $current);
}
```

hmm, but that results in negative balance, which is not allowed.

2022-05-29 14:39 UTC, SOF3 commented
Oh, actually that doesn't work with `payAdaptive`. `payAdaptive` only works with two players, but we want to use it with add/take money.
What about we also add `takeAdaptive` and `addAdaptive`? But that sounds... weird.

2022-06-03 04:12 UTC, JavierLeon9966 commented
Why not just call it `setMoney()` and it will do a similar thing as `payAdaptive()`, get the balance and retry, but it's either going to use `takeMoney()` or `addMoney()` accordingly

2022-06-03 14:54 UTC, SOF3 commented
> Why not just call it `setMoney()` and it will do a similar thing as `payAdaptive()`, get the balance and retry, but it's either going to use `takeMoney()` or `addMoney()` accordingly

sure, I guess that's better.